In [45]:
import pandas as pd
import math
import numpy as np
import itertools

In [46]:
#statsDF - initial stats dataframe
#gamesDF - initial games dataframe
#newGamesDF - formatted games dataframe with game date as index and rest of record in one row
#finalStats - formatted stats dataframe with player's name as the index
#mainDF: The dataframe where the main analysis will take place.

In [83]:
stats = '/home/acer/github/nba/stats.csv'
games = '/home/acer/github/nba/games.csv'

In [106]:
#Dump the stats dataframe into a csv and clean it up
cols = ['PLAYER', 'MIN', 'FGM','FGA', 'FG%', '3PM', '3PA','3P%','FTM','FTA','FT%','OREB','DREB','REB','AST','TOV','STL','BLK','PF','PTS','+/-']
statsDF = pd.read_csv(stats, header= None, names=cols, index_col=False, error_bad_lines=False, delim_whitespace=True)
statsDF[cols] = statsDF[cols].replace({'\$': '', ',': ''}, regex=True)
statsDF['PLAYER'] = statsDF['PLAYER'].str.replace('.','')
statsDF['PLAYER'] = statsDF['PLAYER'].str.replace('-','')
statsDF['PLAYER'] = statsDF['PLAYER'].str.replace("'",'')
statsDF['MIN'] = statsDF['MIN'].str.replace("'",'')
statsDF['MIN'] = statsDF['MIN'].replace({'\$': '', '-': ''}, regex=True)
#Drop the first line for the team name
if statsDF.iloc[0][0] == 'GLOSSARY':
    statsDF.drop([0,1], inplace=True)
else:
    statsDF.drop(0, inplace=True)

In [107]:
#The nba.com site changed its formatting so this is to remove non-existent rows

new_format_mask = 0
for index, row in statsDF.iterrows():
    if new_format_mask == 1:
        statsDF.drop(index, inplace=True)
        if row.iloc[0] == 'Totals:' and math.isnan(row.iloc[1]) == True:
            new_format_mask = 0 
        else:
            continue
    else:
        if row.iloc[0] == 'PLAYER' and row.iloc[1] != "MIN":
            new_format_mask += 1
        else:
            continue

for index, row in statsDF.iterrows():
    if row.iloc[0][3:4] == ":":
        statsDF.drop(index, inplace=True)

In [108]:
statsDF = statsDF[statsDF.PLAYER != 'PLAYER']
statsDF = statsDF[statsDF.PLAYER != 'Totals:']
statsDF = statsDF[statsDF.PLAYER != 'INACTIVE']
statsDF = statsDF.reset_index(drop=True)

In [109]:
#This will delete the second time a team is named. 
for index, row in statsDF.iterrows():
    print(row.iloc[1])
    try: 
        if row.iloc[1].isalpha() and statsDF.iloc[index + 1][1].isalpha() or row.iloc[1] == "76ers":
            #Gallo in game 178 has something weird happening. Need to fix this part
            if row.iloc[1] == 'Gallinari':
                statsDF.insert(index)
            else:
                statsDF.drop(index, inplace=True)
                statsDF = statsDF.reset_index(drop=True)
                break
    except:
        continue

Johnson
0
Griffin
9
Jordan
6
Thornwell
2
Rivers
7
Williams
5
Evans
1
Reed
2
Harrell
3
Johnson
0
Dekker

Gallinari
Williams

Orleans

In [110]:
#Setting up the index on the main stats dataframe
mainDFIndex = []
for index, row in statsDF.iterrows():
    if row.iloc[0] == 'Nene':
        mainDFIndex.append(str(row['PLAYER']) + " " + str(row['MIN']))
    elif row.iloc[0].isalpha() == True and row.iloc[1].isalpha() == True:
        mainDFIndex.append(str(row['PLAYER']) + " " + str(row['MIN']))
print(mainDFIndex)

['Wesley Johnson', 'Blake Griffin', 'DeAndre Jordan', 'Sindarius Thornwell', 'Austin Rivers', 'Lou Williams', 'Jawun Evans', 'Willie Reed', 'Montrezl Harrell', 'Brice Johnson', 'Sam Dekker', 'Danilo Gallinari', 'CJ Williams', 'Dante Cunningham', 'Anthony Davis', 'DeMarcus Cousins', 'ETwaun Moore', 'Jrue Holiday', 'Jameer Nelson', 'Darius Miller', 'Cheick Diallo', 'Ian Clark', 'Tony Allen', 'Charles Cooke', 'Jalen Jones', 'Rajon Rondo']

In [111]:
#Setup dicts from the DF
statsDF_Dict = statsDF.T.to_dict().values()

In [112]:
statsDF

,PLAYER,MIN,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,+/-
0,Wesley,Johnson,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18:25,0,1,0.0,0,1,0.0,0,0,0.0,...,3,3,1,0,2,0,1,0,4,NaN
2,Blake,Griffin,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38:29,9,27,33.3,2,8,25.0,6,7,85.7,...,2,4,6,3,1,0,0,26,-13,NaN
4,DeAndre,Jordan,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,37:06,6,7,85.7,0,0,0.0,0,1,0.0,...,12,14,0,1,2,0,3,12,-5,NaN
6,Sindarius,Thornwell,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,31:52,2,5,40.0,1,2,50.0,2,2,100,...,0,2,2,2,2,0,5,7,-9,NaN
8,Austin,Rivers,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,34:21,7,18,38.9,5,9,55.6,0,0,0.0,...,2,3,2,2,2,0,4,19,-3,NaN
10,Lou,Williams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,36:12,5,16,31.3,1,5,20.0,3,3,100,...,1,2,2,2,2,0,1,14,-9,NaN
12,Jawun,Evans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,23:10,1,6,16.7,1,1,100,8,8,100,...,4,4,3,1,1,0,5,11,-7,NaN
14,Willie,Reed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,10:54,2,2,100,0,0,0.0,3,4,75.0,...,1,1,0,0,0,0,2,7,-3,NaN
16,Montrezl,Harrell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,9:23,3,4,75.0,0,0,0.0,1,2,50.0,...,4,4,0,0,0,1,3,7,5,NaN
18,Brice,Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0:08,0,0,0.0,0,0,0.0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,NaN
20,Sam,Dekker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,DNP,,COACH'S,DECISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Danilo,Gallinari,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,CJ,Williams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,DNP,,COACH'S,DECISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Dante,Cunningham,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,21:27,2,2,100,1,1,100,0,0,0.0,...,2,3,2,1,0,0,2,5,6,NaN
27,Anthony,Davis,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,39:35,9,15,60.0,0,0,0.0,7,9,77.8,...,8,10,5,1,2,2,0,25,11,NaN
29,DeMarcus,Cousins,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,37:10,14,23,60.9,4,8,50.0,3,5,60.0,...,15,15,5,8,0,1,2,35,5,NaN
31,ETwaun,Moore,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,32:41,9,12,75.0,0,1,0.0,0,0,0.0,...,2,4,1,0,1,0,2,18,8,NaN
33,Jrue,Holiday,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,34:53,1,6,16.7,0,2,0.0,4,4,100,...,5,5,8,7,2,0,3,6,0,NaN
35,Jameer,Nelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,28:38,1,6,16.7,0,1,0.0,2,2,100,...,3,3,5,3,1,0,4,4,13,NaN
37,Darius,Miller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,8:50,1,2,50.0,1,1,100,0,0,0.0,...,1,1,0,0,0,1,3,3,-5,NaN
39,Cheick,Diallo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,19:07,4,5,80.0,0,0,0.0,1,2,50.0,...,4,6,0,0,0,0,2,9,0,NaN
41,Ian,Clark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,17:39,2,9,22.2,0,2,0.0,2,2,100,...,3,4,0,3,1,0,1,6,2,NaN
43,Tony,Allen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,DNP,,INJURY/ILLNESS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Charles,Cooke,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,DNP,,COACH'S,DECISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Jalen,Jones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,DNP,,COACH'S,DECISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Rajon,Rondo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,DNP,,INJURY/ILLNESS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
dict_list = []
#Iterate through the statsDF and only return lines with stats or lines where players sat
for index, i in enumerate(statsDF_Dict):
    if index == 1 or index % 2 != 0:
        dict_list.append(i)

In [104]:
finalStats = pd.DataFrame(dict_list)
finalStats.index = mainDFIndex
finalStats.drop(['+/-'], axis=1, inplace=True)
finalStats = finalStats.rename(columns={'PLAYER':'MIN','MIN':'FGM', 'FGM':'FGA', 'FGA':'FG%', 'FG%':'3PM', '3PM':'3PA', '3PA':'3P%', '3P%':'FTM', 'FTM':'FTA', 'FTA':'FT%', 'FT%':'OREB', 'OREB':'DREB', 'DREB':'REB', 'REB':'AST', 'AST':'TOV', 'TOV':'BLK', 'BLK':'PF', 'PF':'PTS', 'PTS':'+/-'})
#This will replace the nan's with DNP
finalStats = finalStats.fillna('NA')
finalStats['Player'] = finalStats.index

ValueError: Length mismatch: Expected axis has 25 elements, new values have 26 elements

In [105]:
finalStats.head()

,+/-,3P%,3PA,3PM,AST,BLK,DREB,FG%,FGA,FGM,...,FTA,FTM,MIN,OREB,PF,PLAYER,PTS,REB,STL,TOV
0,NaN,0,0.0,1,0,1,3,0,0.0,1,...,0.0,0,0,3,0,18:25,4,1,0,2
1,NaN,6,25.0,8,3,0,4,2,33.3,27,...,85.7,7,9,2,26,38:29,-13,6,0,1
2,NaN,0,0.0,0,1,3,14,0,85.7,7,...,0.0,1,6,12,12,37:06,-5,0,0,2
3,NaN,2,50.0,2,2,5,2,1,40.0,5,...,100,2,2,0,7,31:52,-9,2,0,2
4,NaN,0,55.6,9,2,4,3,5,38.9,18,...,0.0,0,7,2,19,34:21,-3,2,0,2

In [47]:
#GAMES CELL: This prepares the games section into a dataframe
#Passing in csv file and getting rid of the unused rows
gamesDF = pd.read_csv(games, header= None, names=['a','b','c','d','e','f','g','h','i'], index_col=False, error_bad_lines=False, delim_whitespace=True)
gamesDF.columns = [col.replace(',', '') for col in gamesDF.columns]
#if you want to operate on multiple columns, put them in a list like so:
games_cols = ['a','b','c','d','e','f','g','h','i']
# pass them to df.replace(), specifying each char and it's replacement:
gamesDF[games_cols] = gamesDF[games_cols].replace({'\$': '', ',': ''}, regex=True)
# This will add the winner to column b of each 26th row
for index, row in gamesDF.iterrows():
    if index % 26 == 0 or index == 0:
        if int(gamesDF['a'].iloc[index+4]) > int(gamesDF['a'].iloc[index + 8]):
            gamesDF['b'].iloc[index] = gamesDF['a'].iloc[index + 1]
        else:
            gamesDF['b'].iloc[index] = gamesDF['a'].iloc[index + 5]
    else:
        pass

In [53]:
#This cell will arrange the gamesDF into the actual formatted games dataframe, newGamesDF
#The next lines will pull the data from the cells in the gamesDF and into the newGamesDF dataframe
gamesData = []
games = 0
for index, row in gamesDF.iterrows():
    if index == 0 or index % 26 == 0:
        gamesData.append(gamesDF.iloc[index+11,0])
        gamesData.append(gamesDF.iloc[index+12,0])
        gamesData.append(gamesDF.iloc[index,1])
        gamesData.append(gamesDF.iloc[index+11,1])
        gamesData.append(gamesDF.iloc[index+11,2])
        gamesData.append(gamesDF.iloc[index+11,3])
        gamesData.append(gamesDF.iloc[index+11,4])
        gamesData.append(gamesDF.iloc[index+12,1])
        gamesData.append(gamesDF.iloc[index+12,2])
        gamesData.append(gamesDF.iloc[index+12,3])
        gamesData.append(gamesDF.iloc[index+12,4])
        gamesData.append(gamesDF.iloc[index+8,0])
        gamesData.append(gamesDF.iloc[index+4,0])
        gamesData.append(gamesDF.iloc[index+22,2])
        gamesData.append(gamesDF.iloc[index+22,4])
        gamesData.append(gamesDF.iloc[index+22,6])
        games += 1
        
gamesData = np.array(gamesData)
gamesData = gamesData.reshape(games,16)
#Create an empty dataframe, based on the games date as the index
newGamesDF = pd.DataFrame(data = gamesData, columns=['Home','Away','W/L','1st Qtr H','2nd Qtr H','3rd Qtr H','4th Qtr H','1st Qtr A','2nd Qtr A','3rd Qtr A','4th Qtr A','Total H','Total A', 'Ref1','Ref2','Ref3'])
newGamesDF

,Home,Away,W/L,1st Qtr H,2nd Qtr H,3rd Qtr H,4th Qtr H,1st Qtr A,2nd Qtr A,3rd Qtr A,4th Qtr A,Total H,Total A,Ref1,Ref2,Ref3
0,NOP,SAC,NEW,27,29,32,26,40,30,17,19,106,114,"Corbin""""","Lindsay""""",Twardoski

In [49]:
for index,row in finalStats.iterrows():
    finalStats['1st Qtr H'] = newGamesDF['1st Qtr H'][0]
    finalStats['2nd Qtr H'] = newGamesDF['2nd Qtr H'][0]
    finalStats['3rd Qtr H'] = newGamesDF['3rd Qtr H'][0]
    finalStats['4th Qtr H'] = newGamesDF['4th Qtr H'][0]
    finalStats['1st Qtr A'] = newGamesDF['1st Qtr A'][0]
    finalStats['2nd Qtr A'] = newGamesDF['2nd Qtr A'][0]
    finalStats['3rd Qtr A'] = newGamesDF['3rd Qtr A'][0]
    finalStats['4th Qtr A'] = newGamesDF['4th Qtr A'][0]
    finalStats['Total H'] = newGamesDF['Total H'][0]
    finalStats['Total A'] = newGamesDF['Total A'][0]
    finalStats['Ref1'] = newGamesDF['Ref1'][0]
    finalStats['Ref2'] = newGamesDF['Ref2'][0]
    finalStats['Ref3'] = newGamesDF['Ref3'][0]
    finalStats['W/L'] = newGamesDF['W/L'][0]
    finalStats['Home'] = newGamesDF['Home'][0]
    finalStats['Away'] = newGamesDF['Away'][0]

In [50]:
#This function will calculate the projected fantasy points per game
def fantasy_points(row):
    try:
        score = (int(row['3PM']) * 3) + (int(row['FGM']) * 2) + (int(row['REB']) * 1) + (int(row['AST']) * 1.5) + (int(row['BLK']) * 3) + (int(row['STL']) * 3) + (int(row['TOV']) * -1)
        return score
    except:
        pass

finalStats['Fantasy Score'] = finalStats.apply(fantasy_points, axis=1)
finalStats = finalStats.fillna('NA')

In [51]:
finalStats.index

Index(['Dante Cunningham', 'Darius Miller', 'DeMarcus Cousins', 'ETwaun Moore',
       'Jrue Holiday', 'Jameer Nelson', 'Cheick Diallo', 'Ian Clark',
       'Tony Allen', 'Charles Cooke', 'Anthony Davis', 'Jalen Jones',
       'Justin Jackson', 'Zach Randolph', 'Willie CauleyStein', 'Buddy Hield',
       'George Hill', 'Kosta Koufos', 'Garrett Temple', 'DeAaron Fox',
       'Skal Labissiere', 'Bogdan Bogdanovic', 'Vince Carter', 'Frank Mason',
       'Malachi Richardson'],
      dtype='object')