In [1]:
import pandas as pd
import numpy as np
import itertools

In [53]:
#statsDF - initial stats dataframe
#gamesDF - initial games dataframe
#newGamesDF - formatted games dataframe with game date as index and rest of record in one row
#finalStats - formatted stats dataframe with player's name as the index
#mainDF: The dataframe where the main analysis will take place.

In [2]:
stats = '/home/acer/github/nba/stats.csv'
games = '/home/acer/github/nba/games.csv'

In [4]:
#Dump the stats dataframe into a csv and clean it up
cols = ['PLAYER', 'MIN', 'FGM','FGA', 'FG%', '3PM', '3PA','3P%','FTM','FTA','FT%','OREB','DREB','REB','AST','TOV','STL','BLK','PF','PTS','+/-']
statsDF = pd.read_csv(stats, header= None, names=cols, index_col=False, error_bad_lines=False, delim_whitespace=True)
statsDF[cols] = statsDF[cols].replace({'\$': '', ',': ''}, regex=True)

In [5]:
statsDF = statsDF[statsDF.PLAYER != 'PLAYER']
statsDF = statsDF[statsDF.PLAYER != 'Totals:']
statsDF = statsDF[statsDF.PLAYER != 'INACTIVE']
statsDF = statsDF.reset_index(drop=True)

In [6]:
statsDF

,PLAYER,MIN,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,+/-
0,Golden,State,Warriors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kevin,Durant,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,40:02,11,24,45.8,4,9,44.4,3,6,50.0,...,11,13,3,6,1,3,2,29,-2,NaN
3,Draymond,Green,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,36:25,1,6,16.7,0,5,0.0,1,2,50.0,...,6,7,6,3,2,1,5,3,-13,NaN
5,Zaza,Pachulia,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,12:12,0,2,0.0,0,0,0.0,0,0,0.0,...,4,6,0,2,2,0,4,0,-5,NaN
7,Klay,Thompson,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,38:11,5,16,31.3,2,8,25.0,2,2,100,...,2,2,1,0,0,1,4,14,0,NaN
9,Stephen,Curry,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,30:04,9,17,52.9,6,11,54.5,13,13,100,...,6,6,3,2,0,0,5,37,-6,NaN
11,Jordan,Bell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,4:15,0,0,0.0,0,0,0.0,0,0,0.0,...,1,2,0,0,0,1,0,0,4,NaN
13,JaVale,McGee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,4:27,1,1,100,0,0,0.0,2,2,100,...,0,0,0,0,0,0,0,4,-8,NaN
15,Andre,Iguodala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,28:43,0,5,0.0,0,2,0.0,0,0,0.0,...,0,2,2,0,2,1,3,0,-4,NaN
17,Patrick,McCaw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,12:23,0,1,0.0,0,1,0.0,0,0,0.0,...,0,0,2,0,1,0,0,0,-9,NaN
19,Shaun,Livingston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,18:05,4,7,57.1,0,0,0.0,0,0,0.0,...,1,2,0,1,0,0,2,8,-7,NaN
21,David,West,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,9:26,1,2,50.0,0,0,0.0,2,2,100,...,3,6,3,2,2,0,2,4,3,NaN
23,Nick,Young,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,5:03,0,2,0.0,0,2,0.0,0,0,0.0,...,0,0,0,1,0,0,0,0,-3,NaN
25,Quinn,Cook,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,0:44,1,1,100,0,0,0.0,0,0,0.0,...,0,0,0,0,0,0,1,2,0,NaN
27,Kevin,Durant,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Draymond,Green,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Zaza,Pachulia,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,21:31,2,4,50.0,1,2,50.0,5,8,62.5,...,1,1,3,1,1,1,5,10,9,NaN
53,Dillon,Brooks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,32:05,4,7,57.1,1,2,50.0,0,1,0.0,...,2,2,2,2,1,1,5,9,0,NaN
55,Tyreke,Evans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,22:58,5,12,41.7,2,5,40.0,0,1,0.0,...,5,7,2,2,1,0,0,12,-2,NaN
57,Chandler,Parsons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,15:14,3,6,50.0,2,4,50.0,0,0,0.0,...,1,1,1,0,0,0,2,8,8,NaN
59,Brandan,Wright,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,11:15,1,1,100,0,0,0.0,0,0,0.0,...,4,4,0,1,1,0,1,2,2,NaN
61,Deyonta,Davis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,DNP,-,COACH'S,DECISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Ivan,Rabb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,DNP,-,COACH'S,DECISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Kobi,Simmons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,DNP,-,COACH'S,DECISION,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,James,Ennis,III,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Jarell,Martin,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Marc,Gasol,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Andrew,Harrison,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Mike,Conley,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Mario,Chalmers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Dillon,Brooks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Tyreke,Evans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Chandler,Parsons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Brandan,Wright,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Deyonta,Davis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Ivan,Rabb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Kobi,Simmons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,GSW:,Omri,"Casspi""""",Kevon,"Looney""""",Damian,"Jones""""",Chris,Boucher,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,MEM:,Ben,"McLemore""""",JaMychal,"Green""""",Wayne,"Selden""""",Vincent,Hunter,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
home_city = []
flag = 0
away_player_count = 0
for index,row in statsDF.iterrows():
    if index == 26 and flag == 0:
        flag = 1
    else:
        if row[0] == 'DNP' or row[0] == 'NWT':
            flag = 1
        else:
            if statsDF.iloc[index + 1][0] == 'DNP' or statsDF.iloc[index + 1][0] == 'NWT':
                continue
            elif flag == 1:
                home_city.append(row[0])
                if index % 2 == 0:
                    home_city.append(statsDF.iloc[-1][0])
                    away_city = [statsDF.iloc[0][0],statsDF.iloc[-2][0]]
                    statsDF = statsDF[statsDF.PLAYER != home_city[1]]
                    statsDF = statsDF[statsDF.PLAYER != away_city[0]]
                    statsDF = statsDF[statsDF.PLAYER != away_city[1]]
                    statsDF = statsDF.reset_index(drop=True)
                    away_player_count = int(statsDF.index[index] / 2)
                    break
                else:
                    home_city.append(statsDF.iloc[-1][0])
                    away_city = [statsDF.iloc[0][0],statsDF.iloc[-2][0]]
                    statsDF = statsDF[statsDF.PLAYER != home_city[0]]
                    statsDF = statsDF[statsDF.PLAYER != home_city[1]]
                    statsDF = statsDF[statsDF.PLAYER != away_city[0]]
                    statsDF = statsDF[statsDF.PLAYER != away_city[1]]
                    statsDF = statsDF.reset_index(drop=True)
                    away_player_count = int(statsDF.index[index] / 2)
                    break
            else:
                continue

In [8]:
#Setting up the index on the main stats dataframe
mainDFIndex = []
for index, row in statsDF.iterrows():
    if index % 2 == 0:
        mainDFIndex.append(str(row['PLAYER']) + " " + str(row['MIN']))
print(mainDFIndex)

['40:02 11', '36:25 1', '12:12 0', '38:11 5', '30:04 9', '4:15 0', '4:27 1', '28:43 0', '12:23 0', '18:05 4', '9:26 1', '5:03 0', '0:44 1', 'Zaza Pachulia', 'Stephen Curry', 'JaVale McGee', 'Patrick McCaw', 'David West', 'Quinn Cook', 'James Ennis', 'Jarell Martin', 'Marc Gasol', 'Andrew Harrison', 'Mike Conley', 'Mario Chalmers', 'Dillon Brooks', 'Tyreke Evans', 'Chandler Parsons', 'Brandan Wright', 'Deyonta Davis', 'Ivan Rabb', 'Kobi Simmons', 'James Ennis', 'Marc Gasol', 'Mike Conley', 'Dillon Brooks', 'Chandler Parsons', 'Deyonta Davis', 'Kobi Simmons']

In [9]:
away_city
away_player_count

13

In [10]:
#Setup dicts with the sub categories
newDict = dict()
something = statsDF.T.to_dict().values()
pos = ''
for index, i in enumerate(something):
    if index % 2 != 0:
        newDict[index] = i
        newDict[index]['POS'] = pos
    else:
        if i['FGM'] == 'nan':
            continue
        else:
            pos = i['FGM']


finalStats = pd.DataFrame.from_dict(newDict,orient='index')
#finalStats.index = mainDFIndex
finalStats.drop(['+/-'], axis=1, inplace=True)
finalStats = finalStats.rename(columns={'PLAYER':'MIN','MIN':'FGM', 'FGM':'FGA', 'FGA':'FG%', 'FG%':'3PM', '3PM':'3PA', '3PA':'3P%', '3P%':'FTM', 'FTM':'FTA', 'FTA':'FT%', 'FT%':'OREB', 'OREB':'DREB', 'DREB':'REB', 'REB':'AST', 'AST':'TOV', 'TOV':'BLK', 'BLK':'PF', 'PF':'PTS', 'PTS':'+/-'})
player_count = len(finalStats.index)
teams_list = ((away_city[0] + " ") * away_player_count) + ((home_city[0] + " ") * (player_count - away_player_count))
teams_list = teams_list.split()
opponent_list = ((home_city[0] + " ") * away_player_count) + ((away_city[0] + " ") * (player_count - away_player_count))
opponent_list = opponent_list.split()
finalStats['Player'] = mainDFIndex
finalStats['TEAM'] = teams_list
finalStats['OPPONENT'] = opponent_list
#This will replace the nan's with DNP
finalStats = finalStats.fillna('NA')

ValueError: Length of values does not match length of index

In [61]:
#GAMES CELL: This prepares the games section into a dataframe
#Passing in csv file and getting rid of the unused rows
gamesDF = pd.read_csv('games.csv', header= None, names=['a','b','c','d','e','f','g','h','i'], index_col=False, error_bad_lines=False, delim_whitespace=True)
gamesDF.columns = [col.replace(',', '') for col in gamesDF.columns]
#if you want to operate on multiple columns, put them in a list like so:
games_cols = ['a','b','c','d','e','f','g','h','i']
# pass them to df.replace(), specifying each char and it's replacement:
gamesDF[games_cols] = gamesDF[games_cols].replace({'\$': '', ',': ''}, regex=True)
# This will add the winner to column b of each 26th row
for index, row in gamesDF.iterrows():
    if index % 26 == 0 or index == 0:
        if int(gamesDF['a'].iloc[index+4]) > int(gamesDF['a'].iloc[index + 8]):
            gamesDF['b'].iloc[index] = gamesDF['a'].iloc[index + 1]
        else:
            gamesDF['b'].iloc[index] = gamesDF['a'].iloc[index + 5]
    else:
        pass

In [62]:
#This cell will arrange the gamesDF into the actual formatted games dataframe, newGamesDF
#Setting up the index on the main stats dataframe
dateIndex = []
month = ['OCT', 'NOV', 'DEC', 'JAN', 'FEB']
for index, row in gamesDF.iterrows():
    for i in month:
        if gamesDF.iloc[index][0] == i:
            dateIndex.append(gamesDF.iloc[9,0] + " " + gamesDF.iloc[9,1][1] + ", " + gamesDF.iloc[9,2])
#The next lines will pull the data from the cells in the gamesDF and into the newGamesDF dataframe
gamesData = []
games = 0
for index, row in gamesDF.iterrows():
    if index == 0 or index % 26 == 0:
        gamesData.append(gamesDF.iloc[index+11,0])
        gamesData.append(gamesDF.iloc[index+12,0])
        gamesData.append(gamesDF.iloc[index,1])
        gamesData.append(gamesDF.iloc[index+11,1])
        gamesData.append(gamesDF.iloc[index+11,2])
        gamesData.append(gamesDF.iloc[index+11,3])
        gamesData.append(gamesDF.iloc[index+11,4])
        gamesData.append(gamesDF.iloc[index+12,1])
        gamesData.append(gamesDF.iloc[index+12,2])
        gamesData.append(gamesDF.iloc[index+12,3])
        gamesData.append(gamesDF.iloc[index+12,4])
        gamesData.append(gamesDF.iloc[index+8,0])
        gamesData.append(gamesDF.iloc[index+4,0])
        gamesData.append(gamesDF.iloc[index+22,2])
        gamesData.append(gamesDF.iloc[index+22,4])
        gamesData.append(gamesDF.iloc[index+22,6])
        games += 1
        
gamesData = np.array(gamesData)
gamesData = gamesData.reshape(games,16)
#Create an empty dataframe, based on the games date as the index
newGamesDF = pd.DataFrame(data = gamesData, columns=['Home','Away','W/L','1st Qtr H','2nd Qtr H','3rd Qtr H','4th Qtr H','1st Qtr A','2nd Qtr A','3rd Qtr A','4th Qtr A','Total H','Total A', 'Ref1','Ref2','Ref3'])
newGamesDF

,Home,Away,W/L,1st Qtr H,2nd Qtr H,3rd Qtr H,4th Qtr H,1st Qtr A,2nd Qtr A,3rd Qtr A,4th Qtr A,Total H,Total A,Ref1,Ref2,Ref3
0,NYK,OKC,OKLAHOMA,24,18,17,25,27,26,26,26,105,84,"Capers""""","Buchert""""",Ford

In [63]:
for index,row in finalStats.iterrows():
    finalStats['1st Qtr H'] = newGamesDF['1st Qtr H'][0]
    finalStats['2nd Qtr H'] = newGamesDF['2nd Qtr H'][0]
    finalStats['3rd Qtr H'] = newGamesDF['3rd Qtr H'][0]
    finalStats['4th Qtr H'] = newGamesDF['4th Qtr H'][0]
    finalStats['1st Qtr A'] = newGamesDF['1st Qtr A'][0]
    finalStats['2nd Qtr A'] = newGamesDF['2nd Qtr A'][0]
    finalStats['3rd Qtr A'] = newGamesDF['3rd Qtr A'][0]
    finalStats['4th Qtr A'] = newGamesDF['4th Qtr A'][0]
    finalStats['Total H'] = newGamesDF['Total H'][0]
    finalStats['Total A'] = newGamesDF['Total A'][0]
    finalStats['Ref1'] = newGamesDF['Ref1'][0]
    finalStats['Ref2'] = newGamesDF['Ref2'][0]
    finalStats['Ref3'] = newGamesDF['Ref3'][0]
    finalStats['W/L'] = newGamesDF['W/L'][0]
    finalStats['Home'] = newGamesDF['Home'][0]
    finalStats['Away'] = newGamesDF['Away'][0]

In [64]:
#This function will calculate the projected fantasy points per game
def fantasy_points(row):
    try:
        score = (int(row['3PM']) * 3) + (int(row['FGM']) * 2) + (int(row['REB']) * 1) + (int(row['AST']) * 1.5) + (int(row['BLK']) * 3) + (int(row['STL']) * 3) + (int(row['TOV']) * -1)
        return score
    except:
        pass

finalStats['Fantasy Score'] = finalStats.apply(fantasy_points, axis=1)
finalStats = finalStats.fillna('NA')

In [65]:
finalStats['Player']

1           Tim Hardaway
3     Kristaps Porzingis
5            Enes Kanter
7           Courtney Lee
9         Ramon Sessions
11          Lance Thomas
13             Ron Baker
15        Doug McDermott
17       Michael Beasley
19          Kyle O'Quinn
21       Frank Ntilikina
23     Willy Hernangomez
25        Damyean Dotson
27           Paul George
29       Carmelo Anthony
31          Steven Adams
33        Andre Roberson
35     Russell Westbrook
37          Alex Abrines
39          Jerami Grant
41     Terrance Ferguson
43        Raymond Felton
45     Patrick Patterson
47        Dakari Johnson
49          Josh Huestis
51         Nick Collison
Name: Player, dtype: object